### ISSUE TITLE
API key name

### ISSUE THREAD

**Issue by zupalex** [terron-kun/tp-notificator#3]
Hello. First I'd like to thank you for this really useful extension.

My only complain so far is that the API key selection is buggy. It displays nothing (literally) so after adding 2 API keys for my own account and my wife's account, it is quite hard to know which one is which because in the drop-down menu, I have the choice between

""
and
""

Which is not really helpful :-)

Cheers

**Comment by flaksp** [comment]
Thank you for opening issue. I don't see any problems in my code. Did you name your API key at [account.arena.net/applications](https://account.arena.net/applications)?

![Screenshot](http://i.imgur.com/ePYxKny.png)

**Comment by zupalex** [comment]
Ahah...ah......ah

I'm sorry, I did not know you could actually name your API key from the GW2 website. I thought that I should somehow give it a "nickname" from within your app.

Sorry for wasting your time and thanks again for the app.

Cheers

**Comment by flaksp** [comment]
However, I'll create an update soon, where API keys with empty name will be named as account name (e.g. "" will be renamed to "terron.3258"). Thanks for the tip.

**Comment by zupalex** [comment]
That's sounds great. Thank you and keep up the good work!

**Comment by zupalex** [comment]
By the way, sorry to spam here and after the issue is closed but I did not want to reopen something for that:

Just a little suggestion. It would be nice to be able to switch between 2 API keys faster directly from the main app menu, instead of having to click the settings to be brought to the general chrome extension settings. Not really important, just a thought :-)

**Comment by flaksp** [comment]
No problem. This will be added in next update too. Everything is done, just waiting for my editor will verify all texts and fix all mistakes in translations.

**Comment by zupalex** [comment]
Awesome.
Do you have a "Donate" or something like that?

Cheers

**Comment by flaksp** [comment]
Sure, contact me via Telegram (`@terron`) or Skype (`terron.home`) please. But better just send some copper to my editor - `kimberly the loser.6129`. She is still playing GW2 and will be happy to get some goods for her job.

**Comment by zupalex** [comment]
Hello.
I do not use any of these 2 stuffs (yeah I know, you're probably like "not
even skype??" but... yeah).

Don't you just have a paypal address I can send a few bucks to? :-)

Cheers

**Comment by flaksp** [comment]
Never used PayPal so I hope I've set up everything correctly: [paypal.me/norret](https://paypal.me/norret)

**Comment by zupalex** [comment]
Sorry you went through all that trouble, I just wanted to donate a small
tip as a thank you.
I suggest in your next update, you add a link to this paypal so people can
easily give random amount to support your work :-)

Cheers

**Comment by zupalex** [comment]
Hello,
for some reason I cannot process through sending the money via paypal. I
don't know if it is some kind of a protection because we are not based in
the same country. Sorry for the disturbance.

Cheers

On Wed, Sep 14, 2016 at 12:11 PM, Alex Lepailleur <alex.lepailleur@gmail.com

> wrote:
> 
> Sorry you went through all that trouble, I just wanted to donate a small
> tip as a thank you.
> I suggest in your next update, you add a link to this paypal so people can
> easily give random amount to support your work :-)
> 
> Cheers
>
